Traceback (most recent call last):
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pathlib
hms_1964 = pathlib.Path("data/full_text/hms_1964_GibsonDanielGIII.txt")
hms_1964_text = hms_1964.read_text()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-2-29b1efa48179>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mpathlib[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mhms_1964[0m [0;34m=[0m [0mpathlib[0m[0;34m.[0m[0mPath[0m[0;34m([0m[0;34m"data/full_text/hms_1964_GibsonDanielGIII.txt"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mhms_1964_text[0m [0;34m=[0m [0mhms_1964[0m[0;34m.[0m[0mread_text[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py[0m in [0;36mread_text[0;34m(self, encoding, errors)[0m
[1;32m   1253[0m         [0mOpen[0m [0mthe[0m [0mfile[0m [0;32min[0m [0mtext[0m [0mmode[0m[0;34m,[0m [0mread[0m [0mit[0m[0;34m,[0m [0;32mand[0m [0mclose[0m [0mthe[0m [0mfile[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1254[0m         """
[0;32m-> 1255[0;31m         [0;32mwith[0m [0mself[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mmode[0m[0;34m=[0m[0;34m'r'[0m[0;34m,[0m [0mencoding[0m[0;34m=[0m[0mencoding[0m[0;34m,[0m [0merrors[0m[0;34m=[0m[0merrors[0m[0;34m)[0m [0;32mas[0m [0mf[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1256[0m             [0;32mreturn[0m [0mf[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1257[0m [0;34m[0m[0m

[0;32m/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py[0m in [0;36mopen[0;34m(self, mode, buffering, encoding, errors, newline)[0m
[1;32m   1239[0m         [0mthe[0m [0mbuilt[0m[0;34m-[0m[0;32min[0m [0mopen[0m[0;34m([0m[0;34m)[0m [0mfunction[0m [0mdoes[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1240[0m         """
[0;32m-> 1241[0;31m         return io.open(self, mode, buffering, encoding, errors, newline,
[0m[1;32m   1242[0m                        opener=self._opener)
[1;32m   1243[0m [0;34m[0m[0m

[0;32m/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py[0m in [0;36m_opener[0;34m(self, name, flags, mode)[0m
[1;32m   1107[0m     [0;32mdef[0m [0m_opener[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m,[0m [0mflags[0m[0;34m,[0m [0mmode[0m[0;34m=[0m[0;36m0o666[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1108[0m         [0;31m# A stub for the opener argument to built-in open()[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1109[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_accessor[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mflags[0m[0;34m,[0m [0mmode[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1110[0m [0;34m[0m[0m
[1;32m   1111[0m     [0;32mdef[0m [0m_raw_open[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mflags[0m[0;34m,[0m [0mmode[0m[0;34m=[0m[0;36m0o777[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'data/full_text/hms_1964_GibsonDanielGIII.txt'
FileNotFoundError: [Errno 2] No such file or directory: 'data/full_text/hms_1964_GibsonDanielGIII.txt'

